apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-app.fullname" . }}
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: http
  selector:
    {{- include "generic-app.selectorLabels" . | nindent 4 }}
