name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    env:
      TELESCOPE_ENABLED: false
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.4'
        ini-values: memory_limit=512M
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
    - name: Start LDAP
      run: |
        docker run -d --name ldap \
          -p 389:389 \
          -e LDAP_ORGANISATION="Demo" \
          -e LDAP_DOMAIN="example.com" \
          -e LDAP_ADMIN_PASSWORD="admin" \
          -v "${GITHUB_WORKSPACE}/.github/ldap/memberof.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/memberof.ldif" \
          osixia/openldap:1.5.0 --copy-service
        until docker exec ldap ldapsearch -x -H ldap://localhost -b dc=example,dc=com -D 'cn=admin,dc=example,dc=com' -w admin > /dev/null 2>&1; do
          sleep 2
        done
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.sample', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Install Node Dependencies
      run: npm ci
    - name: Build Assets
      run: npm run build
    - name: Directory Permissions
      run: |
        mkdir -p storage/framework/views storage/framework/sessions storage/framework/cache storage/app/purifier
        chmod -R 777 storage bootstrap/cache
    - name: Generate key
      run: php -r "file_put_contents('.env', preg_replace('/^APP_KEY=.*/m', 'APP_KEY=base64:'.base64_encode(random_bytes(32)), file_get_contents('.env')));"
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute Feature tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test --testsuite=Feature
    - name: Execute AccountManagerLdap tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
        ACCOUNTMANAGER_DRIVER: ldap
        PROVIDER: ldap
        LDAP_HOST: localhost
        LDAP_PORT: 389
        LDAP_USERNAME: "cn=admin,dc=example,dc=com"
        LDAP_PASSWORD: admin
        LDAP_BASE_DN: "dc=example,dc=com"
        LDAP_TLS: false
      run: php artisan test --testsuite=AccountManagerLdap
